### ISSUE TITLE
[AI/HS2] Timeline doesn't start

### ISSUE THREAD

**Issue by kkykkykky** [IllusionMods/HSPlugins#10]
Timeline version 1.1.4

Problem: `Init()` never ran in AI/HS2 so Timeline couldn't get started. If it is intentional, please close this.

Fix: change [line 334 in Timeline.cs](https://github.com/IllusionMods/HSPlugins/blob/fa5c8d8c46c88ce68d4ea9df88a1da38ab135d93/Timeline.Core/Timeline.cs#L334) to `#elif SUNSHINE || HONEYSELECT2 || AISHOUJO`

**Comment by ManlyMarco** [comment]
Can you make a PR for this change? Just edit the file in the web editor, no need to fork.

**Comment by kkykkykky** [comment]
Ok. Done. Thanks!

**Comment by ManlyMarco** [comment]
Merged the PR
