### ISSUE TITLE
kkpe.dll 2.18 removed all body blend shapes

### ISSUE THREAD

**Issue by yarrmateys** [IllusionMods/HSPlugins#100]
this is best seen with sac kupaa uncensor body since it has a bunch of extra blendshapes of its own. in the newest version those are no longer found anywhere. it added a new slot, nonMatched which i'm guessing is where they could be moved, but the place is empty regardless of what's selected, plus the size of the window changes. the groups get much wider while the blend shapes part itself gets much smaller.
![missing](https://github.com/user-attachments/assets/6cdb745f-51e5-4bfa-a2f0-f2bbfc3424ba)

**Comment by ManlyMarco** [comment]
@ReafLife

**Comment by ReafLife** [comment]
[KKPE.zip](https://github.com/user-attachments/files/18233856/KKPE.zip)
It has been modified, so please check it with this

**Comment by yarrmateys** [comment]
seems to be working so far.
