### ISSUE TITLE
[KK] VideoExport incompatibility with BepisPlugins r18.0

### ISSUE THREAD

**Issue by EveKaczmarek** [IllusionMods/HSPlugins#13]
Newest [BepisPlugins r18.0](https://github.com/IllusionMods/BepisPlugins/releases/tag/r18.0) breaks the UI of VideoExport. Rollback to previous version resolves this issue.

**Comment by ManlyMarco** [comment]
It seems to work fine, are you sure you have the latest version of VideoExport?

**Comment by EveKaczmarek** [comment]
Testing with **KK_HSPlugins_2022.03.01**, **VideoExport 1.2.4** and **BepisPlugins r18.0**
![screenshot](https://user-images.githubusercontent.com/52298587/158273421-8acd000c-41e3-4fe9-930b-1162280d56bd.png)

BepInEx log is getting filled with this error after I open VideoExport UI:
```
[Error  : Unity Log] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
Stack trace:
IScreenshotPlugin System.Collections.Generic.List<VideoExport.ScreenshotPlugins.IScreenshotPlugin>.get_Item(int)
void VideoExport.VideoExport.Window(int)
void UnityEngine.GUI.CallWindowDelegate(WindowFunction, int, int, GUISkin, int, float, float, GUIStyle)
```

**Comment by ManlyMarco** [comment]
Try resetting settings of the plugin from plugin settings or by removing the cfg file.

**Comment by EveKaczmarek** [comment]
Still nothing. Cfg file was created from scratch and didn't changed at all, except the first string with plugin version.
```
## Settings file was created by plugin VideoExport v1.2.4
```

**Comment by ManlyMarco** [comment]
[KK_BepisPlugins_r18.0.1.zip](https://github.com/IllusionMods/HSPlugins/files/8249206/KK_BepisPlugins_r18.0.1.zip)
Does this fix the issue? Please check if recording normal/alpha still works.

**Comment by EveKaczmarek** [comment]
Yup, now everything seems alright. Here's screenshots with transparency that captured with r18.0.1 screencap, rgAlpha on top.
![CharaStudio-2022-03-15-03-42-05-Render](https://user-images.githubusercontent.com/52298587/158284125-ae49f42f-835c-44e9-b0a8-05b129e67b6d.png)
![CharaStudio-2022-03-15-03-42-19-Render](https://user-images.githubusercontent.com/52298587/158284121-b9a0c742-a694-499b-ad38-ff67f0580719.png)
