### ISSUE TITLE
[KKS][VideoExport]Unstable operation of ffmpeg-64 included in VideoExport.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/HSPlugins#21]
Unstable operation of ffmpeg-64 included in VideoExport.

After a long capture and during encoding, the task may stop working.
In that case, for some reason, exiting CharaStudio seems to restart the ffmpeg-64 task. (CPU usage in taskmanager will increase and file size writing will resume)
I have had the same situation twice in the past, but by closing CharaStudio, ffmpeg was activated and I was able to export to the end of the file.
I am not sure how to reproduce the error condition, but I will report it.
This text was translated using deepl.

**Comment by ManlyMarco** [comment]
Maybe you ran out of RAM? Closing CharaStudio would free up a lot of RAM and potentially let ffmpeg continue.

**Comment by ManlyMarco** [comment]
I updated ffmpeg in https://github.com/IllusionMods/HSPlugins/commit/bf842a7ddc496107360c39b6812f76f46215b8ab
If that doesn't fix the issue then most likely something is wrong on your end, probably running out of RAM like I mentioned. This change should get released in a couple of days. Feel free to reopen the issue if the issue persists in the upcoming release.
