### ISSUE TITLE
[timeline]vital issue, after use function"group together", when changing chara, timeline will be unable to play.

### ISSUE THREAD

**Issue by mrxuzhen** [IllusionMods/HSPlugins#26]
Many timeline author like to use function "group together" to make interpolables logically assessable. But in hf-patch's timeline, after using "group together" function before I replace the chara, the whole timeline will be messed up. Those interpolables will be blended into together and I can no longer delete replaced chara. The whole plugin will be broken. Actually in original version of timeline by joan6694 have no such a big problem, though his version have many bugs, but none of them are so vital.

In logs there wil be many loop error.
And most importantly, when using latest timeline to make a scene card, such a problem will sustain, even this card is loaded in old version of timeline. That means when such issue happens, the card saved in latest timeline plugin will never be able to replace charater.
---------------------------------------------------------------------

NullReferenceException: Object reference not set to an instance of an object
at HSPE.AMModules.DynamicBonesEditor/TimelineCompatibility/<>c.<Populate>b__1_14 (string,Studio.ObjectCtrlInfo,object) <0x00055>
at Timeline.Interpolable.get_name () <0x00059>
at Timeline.Timeline.ShouldShowInterpolable (Timeline.Interpolable,bool) <0x0008d>
at Timeline.Timeline/<>c__DisplayClass173_0.<UpdateInterpolablesViewTree>b__1 (Timeline.LeafNode`1<Timeline.Interpolable>) <0x00031>
at Timeline.Tree`2<Timeline.Interpolable, Timeline.Timeline/InterpolableGroup>.Any (Timeline.GroupNode`1<Timeline.Timeline/InterpolableGroup>,System.Func`2<Timeline.LeafNode`1<Timeline.Interpolable>, bool>) <0x00151>
at Timeline.Timeline.UpdateInterpolablesViewTree (System.Collections.Generic.List`1<Timeline.INode>,bool,int&,int&,single&,int) <0x009fc>
at (wrapper dynamic-method) Timeline.Timeline.DMD<Timeline.Timeline..UpdateInterpolablesView> (Timeline.Timeline) <0x0013e>
at Timeline.Timeline.RemoveInterpolables (System.Collections.Generic.IEnumerable`1<Timeline.Interpolable>) <0x002d5>
at (wrapper dynamic-method) Timeline.Timeline.DMD<Timeline.Timeline..Update> (Timeline.Timeline) <0x00605>

 
(Filename:  Line: -1)
-----------------------------------------------------------------------------

**Comment by DefectoDetecto** [comment]
For me, after "group together" I can replace characters without any problem. I'm also using the latest hf-patch's timeline.
Maybe you need to provide more specific information to reproduce the issue? or a scene file

**Comment by mrxuzhen** [comment]
https://mega.nz/file/wssHmCZL#DcONfEMKRvJmLCPDU3aOBj5PW67NokKEyPSh8Q1k6VI
this is a charged scene card by yuukis so please don't leak it elsewhere.

**Comment by mrxuzhen** [comment]
there are some other bugs which is not that vital. Such as after "group together", when I tried to ungroup them, I can't just "parent  to nothing" them. After "parent to nothing" them, there will be 2 same interpolables at same time, one in group, one outside the group. After save and load there will be only 1 left, I mean the upper one. That makes ungroup process very complicated.

**Comment by DefectoDetecto** [comment]
Seems that the same issue can be reproduced even with Joan's original 1.1.0 version.

**Comment by mrxuzhen** [comment]
No, maybe it is me who didn't describe it clearly. the broken scenes, whatever what version of timeline the "who load the scene" have, the studio will be broken, old or new, it doesn't make a difference. 
But if you are MAKING scene cards in hf's latest version of timeline, and you use the group together function, the scene card will be broken once saved. Thats different. It means the card is broken when make in latest version. In manlymarco's original version, when card is make in same way, this problem will not happen. 
There must be something different
 between original version and latest version in group together function. There are more and more scene maker are puzzled by this bug.

**Comment by DefectoDetecto** [comment]
I know what you're talking about. But below is the process I tested.
I downloaded a timeline scene created nearby after the 1.1.0 release, used "Group together" with Joan's origianl 1.1.0 Timeline, saved it, and then loaded it.
The same issue happened.

**Comment by mrxuzhen** [comment]
Well, to be honest that I am using 1.1.0 to create scenes for long. Here is one of my scene.
Could you have a try on this scene? I can't make same issue happens to it actually.
![2022_0927_1653_43_097](https://user-images.githubusercontent.com/104879343/192481093-3dc8f454-d38c-491e-9536-953b265a2534.png)

**Comment by DefectoDetecto** [comment]
![timeline](https://user-images.githubusercontent.com/100230290/192483489-4a3e12c5-4daf-4a6a-a9df-84e20acac352.png)
Timeline 1.1.0(So, there is no Timeline button in the left corner) with the HF patch from 2 years ago.
