### ISSUE TITLE
[VideoExport][Screenshot Manager] ScreenFrame is not captured during recording and Screenshot(F11).

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/HSPlugins#27]
In the current Video Export plugin, the frames of the studio scene are not captured, which was already the case when I started using Video Export. However, I have talked to users from long ago and they say that it was possible to record frames.
A similar problem occurs with screenshots by F11.(UI screenshot F9 does not occur but is low resolution.)
Probably for the same reason.
I too would like to record animation frame by frame. Is it possible to respond to the request?

![CharaStudio-2022-10-10-14-47-15-Render](https://user-images.githubusercontent.com/39472846/194805569-c1bd2c29-eae8-47a0-baa0-0add19636fe9.png)
![CharaStudio-2022-10-10-14-47-32-UI](https://user-images.githubusercontent.com/39472846/194805616-d4159cf6-68fc-4e51-991f-83eb2a6c4312.png)

**Comment by leoftm** [comment]
If I should have enhancement it to "BepisPlugins ScreenCap" instead of "HSPlugins VideoExport", I apologize for the misplacement.

**Comment by ManlyMarco** [comment]
Resolved in https://github.com/IllusionMods/BepisPlugins/commit/707e1fe0c0656b5d3d072bdc7934c5131fa16dcb
