### ISSUE TITLE
[VideoExport][KK] bmp export option

### ISSUE THREAD

**Issue by NotMomoK** [IllusionMods/HSPlugins#28]
Is possible bring back to KK version the option to export using .bmp files ?, it takes ages to export a video bigger then 3 minutes in 4k 60 (around 3 hours to 5 hours), when exporting in .bmp it takes around 30 ~ 45 minutes at max even with a 5 minutes mmd motion. I think the KKS version has that option but it was (removed ?) from the KK version for some reason

specs:
Ryzen 7 5800x
32Gb ram
rtx 3060 
nvme gen 4 2Tb

**Comment by ManlyMarco** [comment]
KK is missing necessary dll file inside its managed folder to use bmp capture (System.Drawing.dll). It might have worked in the past if it was added externally, but it doesn't ship with the game or any plugins.
