### ISSUE TITLE
Bonemod in older Scenes not getting Updated when swapping characters

### ISSUE THREAD

**Issue by Nineball459** [IllusionMods/HSPlugins#32]
When opening up older scenes, when swapping out the chika/standin present in the scene for another character, certain ABMX bones do not update and stay at the default amounts, the most noticeable being the hands. If you have a card with large hands made possible using ABMX, the hands will load in disproportionately tiny when swapping the scene's character for your character.

Copying the character does not solve this issue. Saving the scene and reloading it does not solve it either. The only known solution to this is completely deleting KKPE. Rolling back any and all plugins does not fix this issue. Having just KKPE, ABMX and Bepis_Plugins present still results in the issue. Yet strangely enough, loading in a new chika into the scene and swapping your character on them does not produce the issue. This issue is also not present on more recent or brand new scenes, only when loading up older scenes and attempting to swap characters into them.

**Comment by ManlyMarco** [comment]
Does this still happen with ABMX 5.0.5?

**Comment by ManlyMarco** [comment]
Closing as stale, if the issue still happens please reopen.
