### ISSUE TITLE
[KK][VideoExport][Timeline] Timeline recording "Loops To Record 1" does not reach the last frame correctly when TimeScale is changed.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/HSPlugins#34]
If you want to record to the last frame of the timeline using KK_VideoExport, you would set "Limit By" to "Timeline", Prewarm Loop Count: 2, Loops To Record 1.000, etc.
However,If you have changed the Time Scale on the timeline to a number other than 1, this will cause it to be out of sync.
Especially in the case of animations that change the timescale in the middle of the animation, it is very difficult to make the first frame and the last frame of the loop video the same with the current VideoExport.
Is it possible to count the recording loop "1" when it reaches the last frame, regardless of the duration and timescale and Framerate values?

It is possible that it is possible to do one loop recording in all frames in a way that I am not aware of, and if so, I would be glad to know how to do it.

**Comment by ManlyMarco** [comment]
Do you mean that the last frame is not captured? Or are there more than one frame not being captured?

**Comment by leoftm** [comment]
>"Do you mean that the last frame is not captured? Or are there more than one frame not being captured?"
Sorry my explanation is not clear.
If you set the Time Scale to 0.5x, a 1 minute video in Loops To Record 1.000 is actually 2 minutes long, but only 1 minute is recorded.
If it is fixed at 0.5, it is easy to predict, but if it varies from 1 to 0.5 to 2 on the timeline, it becomes difficult to easily determine the end time.
I am currently using a method where I save a longer recording and cut it off later, but this method is also difficult for looping videos that go back to the first frame of the entire video. (It is difficult to make sure that the first and last frames are identical.)
