### ISSUE TITLE
[Request]Add Transparency for PNG Frames by VideoExport

### ISSUE THREAD

**Issue by RyanBram** [IllusionMods/HSPlugins#36]
Hi, Developer.
VideoExport is a great tool to create sprite for game, but unfortunately the current version seems doesn't have support for transparent PNG like F11 Screenshot feature.

Please add this feature which will greatly help for rendering 2D Sprite from Studio.

Thanks

**Comment by ManlyMarco** [comment]
Are you sure? I'm pretty sure it does support transparency, you just have to use the right recording mode. If all else fails, turning off removing frames and use them directly.
