### ISSUE TITLE
HS2PE's emoticon presets cannot be loaded for different characters.

### ISSUE THREAD

**Issue by wenlee666** [IllusionMods/HSPlugins#37]
I am not a native English speaker. Sorry for my poor English.

In order to make the expression presets can be shared online, I modified the source code of BlendShapesEditor part of HS2PE, which can be used by most people after testing.

I fix the ".dll",But I don't know how to release

**Comment by wenlee666** [comment]
![image](https://user-images.githubusercontent.com/123046464/218302614-53754976-f722-4b0f-bb1c-66b917841d47.png)

**Comment by wenlee666** [comment]
I only changed the LoadPresets function in BlendShapesEditor.

private void LoadPreset(string name)
{
	string[] facetypes = new string[]
	{
		"n_head_cf1",
		"n_head_cf2",
		"n_head_cf2_c1",
		"n head cf3_hs2"
	};
	string faceBoneNow = "";
	string text = Path.Combine(BlendShapesEditor._presetsPath, name);
	if (!File.Exists(text))
	{
		return;
	}
	foreach (SkinnedMeshRenderer meshRenderer in this._skinnedMeshRenderers)
	{
		if (meshRenderer.name == "o_eyelashes")
		{
			faceBoneNow = meshRenderer.transform.parent.name;
		}
	}
	XmlDocument xmlDocument = new XmlDocument();
	xmlDocument.Load(text);
	if (xmlDocument != null)
	{
		foreach (object obj in xmlDocument.FirstChild.FirstChild.ChildNodes)
		{
			XmlNode xml = (XmlNode)obj;
			XmlElement xmlElement = (XmlElement)xml;
			string u = xmlElement.GetAttribute("name");
			int a = u.LastIndexOf("/");
			string s = u.Substring(a);
			int facerenderer = 0;
			if (!(s == "/o_eyelashes"))
			{
				if (!(s == "/o_tang"))
				{
					if (s == "/o_tooth")
					{
						facerenderer = 3;
					}
				}
				else
				{
					facerenderer = 2;
				}
			}
			else
			{
				facerenderer = 1;
			}
			string u2 = u.Substring(0, u.Length - s.Length);
			int a2 = u2.LastIndexOf("/");
			string faceBone = u2.Substring(a2);
			string value = u2.Substring(0, u2.Length - faceBone.Length) + "/" + faceBoneNow + s;
			string facebone = faceBone.Substring(1, faceBone.Length - 1);
			if (facebone != faceBoneNow)
			{
				int x = 0;
				int x2 = 0;
				int x3 = 0;
				foreach (string a3 in facetypes)
				{
					x++;
					if (a3 == facebone)
					{
						x2 = x;
					}
					if (a3 == faceBoneNow)
					{
						x3 = x;
					}
				}
				xmlElement.SetAttribute("name", value);
				foreach (object obj2 in xml.ChildNodes)
				{
					XmlElement element2 = (XmlElement)((XmlNode)obj2);
					int index = XmlConvert.ToInt32(element2.GetAttribute("index"));
					switch (facerenderer)
					{
					case 1:
						switch (x2)
						{
						case 1:
							if (x3 == 2)
							{
								if (index == 0)
								{
									index = 16;
								}
								index--;
							}
							break;
						case 2:
							if (index == 15)
							{
								index = -1;
							}
							index++;
							break;
						case 3:
							if (x3 == 2)
							{
								if (index == 0)
								{
									index = 16;
								}
								index--;
							}
							break;
						}
						break;
					case 2:
						switch (x2)
						{
						case 1:
							if (index == 0)
							{
								index = 7;
							}
							index--;
							break;
						case 2:
							if (x3 == 1)
							{
								if (index == 6)
								{
									index = -1;
								}
								index++;
							}
							break;
						case 3:
							if (x3 == 1)
							{
								if (index == 6)
								{
									index = -1;
								}
								index++;
							}
							break;
						}
						break;
					case 3:
						switch (x2)
						{
						case 1:
							if (index == 0)
							{
								index = 7;
							}
							index--;
							break;
						case 2:
							if (x3 == 1)
							{
								if (index == 6)
								{
									index = -1;
								}
								index++;
							}
							break;
						case 3:
							if (x3 == 1)
							{
								if (index == 6)
								{
									index = -1;
								}
								index++;
							}
							break;
						}
						break;
					}
					element2.SetAttribute("index", index.ToString());
				}
			}
		}
	}
	this.LoadXml(xmlDocument.FirstChild);
}

**Comment by wenlee666** [comment]
Writing code with decompiler tools is inconvenient, so no additional functions are written to simplify the code.You can optimize it if you want.

At the same time, I also found some minor bugs in the "Link to Eyes component". It appears that the eyes and eyelashes do not match in a default model of a character's face.

The reason I found it was because the index of the "eyelashes" option did not match the index of the "eyes". But I haven't fixed it yet.

**Comment by ManlyMarco** [comment]
Thanks, I'll take a look at this later.

You don't have to edit the dll with dnspy, just download VS2022 and the source code from this repository. HS2PE will build without doing anything special.

**Comment by ManlyMarco** [comment]
If you're still around, can you check if this build works correctly? I added your code but it's not exactly the same so there might be  regressions. [HS2PE.zip](https://github.com/IllusionMods/HSPlugins/files/10934337/HS2PE.zip)

**Comment by wenlee666** [comment]
I'm sorry that I haven't had time to debug and follow up recently, so I can't know how it working of the file you uploaded, but I think I can give you some help.

**1.**This is the file I fixed earlier, and I think it should work 
[HS2PE.dll](https://github.com/wenlee666/1GitHub/raw/master/HS2PE.dll)

**2.**My logic is to change the renderer parameters of the BlendShapePresets file to the renderer corresponding to the character currently selected by the player before the player reads the corresponding BlendShapePresets.
There are two main aspects. One is the face shape(type) parameter, and the other is the sequence conversion of different face shapes(type) renderers.
The face shape(type) in the file can only be read if it corresponds to the face of the character currently selected by the player.
If the renderer order changes, the code for the transformation also has to change.

**3.**Not only that, the path of the BlendShapePresets file can also affect the execution of the plugin.
Old path of the emoji preset save location: BepInEx\Plugins\HS2PE\BlendShapesPresets
New path of the emoticon preset location: UserData\HS2PE\BlendShapesPresets
This can cause problems if you read from an older version path.

**Comment by ManlyMarco** [comment]
I merged and released the fix. For now I only enabled it in AIPE and HS2PE. If it also works in KK and KKS please let me know.
