### ISSUE TITLE
[KKPE] Duplicating objects causes parenting to break

### ISSUE THREAD

**Issue by gievepix** [IllusionMods/HSPlugins#58]
Duplicating objects sometimes can cause parenting break completely: after clicking "parent" button supposed child object moves under parent in workspace, but both remain selected (this is how you know you got this bug), and parenting doesn't actually happen. In this case, parenting just breaks completely and won't work until you reset scene, after reloading "child" object can either remain unparented, or just disappear as if it never existed.
There are various cases when it happens, but the only reliable way to reproduce it I found is:
1) add character to scene
2) add new object (item or folder)
3) parent this object to any part of character
4) parent it to any other part of character (I don't know why, but single parenting isn't enough)
5) duplicate it
6) delete original
7) attempt to parent copy (or anything really) to anything -> it breaks

After a bit more testing I found that after step 4 you can duplicate copy and parent new copy to different part of character all you want, but if you delete **any** object in this chain, next parenting will break even if it's not related to these them at all...
If you load scene that has some character with objects parented to its parts, steps 1-4 can be omitted.

Tagging it as PE issue because it's PE that throws errors in log whenever this bug happens, and removing it immediately gets rid of this issue. I believe it was fixed in 2.4.1.1 (at least I don't remember getting it since then), but recently came back, probably in 2.7.1?

**Comment by takahiro0327** [comment]
Try this. You know how to use dll's, right?  
If you try it, be sure to let me know how it turns out.
[KKSPE.zip](https://github.com/IllusionMods/HSPlugins/files/14094300/KKSPE.zip)
[KKPE.zip](https://github.com/IllusionMods/HSPlugins/files/14094309/KKPE.zip)



<sup>I didn't want it to be because of my past fixes, so I looked into it. In addition, I fixed it. As you can see from other issues, it is usually left alone. Please be careful not to ask others for quick fixes.</sup>

**Comment by takahiro0327** [comment]
Thanks for confirming.

As long as development continues, someone will step on another landmine.
The complexity of these mods is considerable.
Either stop using them, or better yet, you create a perfect, bug-free replacement.
