### ISSUE TITLE
[NodesConstraints]Scale values are wrong.

### ISSUE THREAD

**Issue by Makao1240** [IllusionMods/HSPlugins#71]
Since the new version, the behavior when constraining the scale is strange.
Perhaps there is a problem with the following code.
Could `originalParentScale.x` be a typo?

https://github.com/IllusionMods/HSPlugins/blob/5cff07434a228f0c75bfcc415779df5ac7c95732/NodesConstraints.Core/NodesConstraints.cs#L255-L261

Thanks again for all the great plugins!
This major update has been great as well!
Hope this glitch gets fixed.

(DeepL: JPN→ENG)

**Comment by ManlyMarco** [comment]
@RikkiBalboa
