### ISSUE TITLE
HS2: BetterPenetration 5.0.1 conflict with NodesConstraints 1.3.0 ( OK with NodesConstraints 1.2.4)

### ISSUE THREAD

**Issue by wgtboy** [IllusionMods/HSPlugins#73]
Here are the versions of related plugins:
BetterPenetration 5.0.1 
NodesConstraints 1.3.0
UncensorSelector 3.11.8

The following error occurred during studio startup, BetterPenestration cannot work in the studio, and the related menu disappears. It 
 also cannot work in the normal game mod.

[Info   : Unity Log] Studio_BetterPenetration: patched UncensorSelectorController::ReloadCharacterBalls correctly
[Error  : Unity Log] AmbiguousMatchException: Ambiguous match found.
Stack trace:
System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) (at <7ba07f088431485bb722f3b3373e87ee>:0)
System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) (at <7ba07f088431485bb722f3b3373e87ee>:0)
HarmonyLib.AccessTools+<>c__DisplayClass18_0.<Method>b__0 (System.Type t) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.AccessTools.FindIncludingBaseTypes[T] (System.Type type, System.Func`2[T,TResult] func) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.AccessTools.Method (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as AmbiguousMatchException: Ambiguous match in Harmony patch for NodesConstraints.NodesConstraints:AddConstraint
HarmonyLib.AccessTools.Method (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HS2_Studio_BetterPenetration.HS2_Studio_BetterPenetration.Main () (at <ea6a69b4eccc4bd6bc8c460a5cecdf80>:0)

**Comment by wgtboy** [comment]
Ok, thanks a lot! And I had got it from your post :)

**Comment by ManlyMarco** [comment]
Closing since a fixed version of BP was already released here https://github.com/IllusionMods/BetterPenetration/releases/tag/5.0.1.1
